### ISSUE TITLE
Why use choice when generating data instead of iterating through all subjects?

### ISSUE THREAD

**Issue by xerrors** [zhao9797/RIFRE#4]
Hello, zhao9797, first of all, thank you for your outstanding contribution and open source the code of the project, and the readability of the code is also excellent; however, I encountered a small problem in the process of reading, so I would like to ask for some advice.

When generating the data, the mapping relationships of all the triples for each sentence are stored in a variable called `s2ro_map`, but when generating the data, why is it that only one of the subjects is randomly selected from all the subjects, as in the following code.

https://github.com/zhao9797/RIFRE/blob/ba708806444d9ad4afb824436a368b12215048e4/framework/dataloaders.py#L79

I simply debugged it and found that there are multiple subjects in some sentences.

![image](https://user-images.githubusercontent.com/35524243/133015781-2efe72d5-6f19-46c9-a77f-1a8e4e7f9ac9.png)

So shouldn't we iterate through all the subjects here? I have seen similar operations in other projects' code, which also greatly deepened my doubts.

(By Translator) 

---
简体中文：

你好，zhao9797，首先很感谢你做出的突出贡献并将项目的代码开源，同时代码的可读性也是极好的；但是我在阅读的过程中遇到了一个小问题，所以来请教一下。

在生成数据的时候，对于每一个句子的所有三元组的映射关系都保存在了 叫做`s2ro_map` 的变量里面， 但是在生成数据的时候为什么只是从所有的 subject 里面随机选择了一个，如下面的代码：

https://github.com/zhao9797/RIFRE/blob/ba708806444d9ad4afb824436a368b12215048e4/framework/dataloaders.py#L79

我简单调试了一下，发现在部分句子中是会存在多个 subject 的情况：

![image](https://user-images.githubusercontent.com/35524243/133015781-2efe72d5-6f19-46c9-a77f-1a8e4e7f9ac9.png)

所以这里难道不应该遍历所有的 subject 吗？我在其他项目的代码中也看到了类似的操作，这也大大加深了我的疑惑。

**Comment by zhao9797** [comment]
这里如果遍历所有的subject，将十分耗费时间和资源而且还没必要。利用采样的方法，随着训练进行，几乎会采样到所有可能的主语，这样就会使数据得到充分训练而且还省时。

**Comment by xerrors** [comment]
多谢！明白了！
