### ISSUE TITLE
数据集相关问题

### ISSUE THREAD

**Issue by jingjingliu1998** [zhao9797/RIFRE#8]
请问可以讲解一下关于NYT和WebNLG数据集的处理步骤吗？不知道是否是数据集处理的不恰当，在使用这两个数据集的时候代码出现too many values to  unpack的报错，希望得到答复，感谢

**Comment by zhao9797** [comment]
这两个数据集的处理用的是CasRel的[脚本](https://github.com/weizhepei/CasRel/tree/master/data)，没有做其他的特殊处理

**Comment by jingjingliu1998** [comment]
请问可以分享一下处理完的数据集吗？这个两个数据集我按照CasRel的步骤处理，不知道是否出现错误






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhao9797/RIFRE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 中午1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhao9797/RIFRE] 数据集相关问题 (Issue #8)





 
这两个数据集的处理用的是CasRel的脚本，没有做其他的特殊处理
